# Generated by Django 2.0.7 on 2018-08-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180814_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
