# Generated by Django 2.0.7 on 2018-08-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180822_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.CharField(default='https://d2787ndpv5cwhz.cloudfront.net/a51b5f179788e296483d6f5dee2e3b1c254becb5/300x300.jpg', max_length=255, null=True),
        ),
    ]
